yueqiu:
  name: yueqiu
  version: 4.7.6
  copyrightYear: 2023
  demoEnabled: false
  profile: D:/yueqiu/uploadPath
  addressEnabled: true
  captchaType: number


spring:
  jackson:
    time-zone: GMT+8
  profiles:
    active: druid
  messages:
    basename: i18n/messages
    encoding: UTF-8


  mail:
    host: smtp.163.com
    password: OLRYMKBDOGSWDHDC
    username: qqqq1393553001@163.com
    # 发送邮件服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8




  redis:
    port: 6379
    host: 127.0.0.1
    password:
    database: 2
    # 连接超时时间
    timeout: 10s
    jedis:
      pool:
        max-active: 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381

  session:
    store-type: redis
server:
  port: 8080


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30



mybatis:
  #  多个package路径用 ',' 隔开
  type-aliases-package: com.yueqiu.**.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10


swagger:
  isSwaggerEnabled: true
